### ISSUE TITLE
Syntax Error in main.py line 56

### ISSUE THREAD

**Issue by SecretUser001** [Quoorex/minecraft-server-eu-bot#1]
File "main.py", line 56
profile.set_preference(f"network.proxy.{p_type}", host)
°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°^
SyntaxError: invalid syntax

(Ignore °)

**Comment by Quoorex** [comment]
That error probably shows up because you aren't using Python 3.6 or higher.

**Comment by Quoorex** [comment]
Also make sure that you installed the pipenv with `pipenv install` and have it enabled by running `pipenv shell`. After that you can start the program with `python main.py`
