### ISSUE TITLE
Buster not being able to solve a captcha causes the whole program to quit

### ISSUE THREAD

**Issue by Quoorex** [Quoorex/minecraft-server-eu-bot#3]
The program installs the Firefox Extension Buster which is used the solve the captchas. Buster listens to the audio version of the Recaptcha and uses a public Text-to-Speech API to translate that audio into text. That text is then entered and the captcha thereby solved. The problem is that this API has a limit as to how often it can be used per minute. All Buster Users together count towards that limit because they all use the same API key provided by the developer of Buster. That means if too many users use Buster at the same time, it fails to solve the captcha.
The bot currently does not handle this correctly and produces a error (or so I think). What can be done is to either let the bot retry solving the captcha with Buster until it works, or to implement a captcha solving service into the program, which would also make it run faster.

This has also been mentioned in #2

**Comment by Dibsymodzz** [comment]
somehow it doesn't work cover-free
