### ISSUE TITLE
what are the best proxies for the tool

### ISSUE THREAD

**Issue by Dibsymodzz** [Quoorex/minecraft-server-eu-bot#4]
if I try proxies it doesn't work even though I use hq proxies

**Comment by Quoorex** [comment]
Could you please try again? I've updated the program and proxies should work fine now. But login credentials for the proxies aren't supported. And also please try using SOCKS or HTTPS proxies. HTTP proxies are kind of weird.

**Comment by Dibsymodzz** [comment]
ok

**Comment by Dibsymodzz** [comment]
what is the best why to bot votes ? 

on windows or what ?

and what is the best config ?

:D

**Comment by Dibsymodzz** [comment]
and i get this error https://prnt.sc/s6etxb

sry for spam

**Comment by olhartley** [comment]
I have that as well, It means that it can’t find the element on the page which refers to the captcha, for instance when you press f12 and look for the captcha box name that is what the program is looking for but can’t find it, I’ve tried different ones but I still can’t find the correct name/id/class name

**Comment by Dibsymodzz** [comment]
ok

**Comment by Dibsymodzz** [comment]
can i fix this  self
