### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by TheDani312** [Quoorex/minecraft-server-eu-bot#7]
Hey, ich komme damit echt überhaut gar nicht klar.. kannst du mir bitte erklären, wie ich das benutzen kann? Und wie ich das zum laufen bringe.

Dankeschön :)

**Comment by Quoorex** [comment]
Ich kann dir nicht einmal mehr versichern, dass das Programm überhaupt noch funktioniert. Ich habe das seit über einem Jahr nicht mehr verwendet. Falls du es trotzdem versuchen möchtest, gebe ich dir eine kurze Anleitung. Wenn du es damit nicht hinbekommst ist dieses Programm wahrscheinlich eher nichts für dich, da es nicht wirklich nutzerfreundlich und eher für Entwickler gedacht ist.

1. Python installieren (den Installer gibt es hier: https://www.python.org/downloads/)
2. dieses Repository herunterladen und die Zipdatei entpacken
3. mit dem Terminal (unter Windows `cmd` bei den Programmen suchen) in den Ordner wechseln (Befehl `cd` nutzen)
4. den Befehl `pip install poetry` und `poetry install` ausführen
5. `poetry shell` eingeben
6. `python main.py`
