### ISSUE TITLE
import Yaml

### ISSUE THREAD

**Issue by Ralphaf** [Quoorex/minecraft-server-eu-bot#8]
File "C:\Users\Owner\Desktop\ALL\minecraft-server-eu-bot-master\main.py", line 18, in <module>
    import Yaml
ModuleNotFoundError: No module named 'Yaml'

**Comment by Quoorex** [comment]
You're missing the pyyaml module. I guess something must have gone wrong during the installation, so feel free to try installing the dependencies again.
